### ISSUE TITLE
[FEAT] 홈화면 구현

### ISSUE THREAD

**Issue by durumi99** [FunD-StockProject/StockProject-Frontend#15]
## 📒 설명
 홈화면(초기화면) 컴포넌트 구현

## ✅ TO-DO
- [x]  공통 컴포넌트 분리
- [x]  인기 종목 컴포넌트 구현
- [x]  급등 / 급락 종목 컴포넌트 구현
- [x] API 연결
- [x] 화살표 구현

## 🔔 기타
-  검색 api 구현 11/9
-
