### ISSUE TITLE
[DEPLOY]: CI/CD 구축

### ISSUE THREAD

**Issue by durumi99** [FunD-StockProject/StockProject-Frontend#75]
## 📒 설명
Github Actions를 통한 CI/CD 구축

## ✅ TO-DO
- [x]  임시 정적 페이지 배포
- [x]  CI 프로세스 구축
- [x]  백엔드 연계
- [x] 배포 뭐로할건지 fix

## 🔔 기타
-
