### ISSUE TITLE
[REFACTOR]:  상태관리 react-query 마이그레이션

### ISSUE THREAD

**Issue by durumi99** [FunD-StockProject/StockProject-Frontend#88]
## 📒 설명
상태관리 react-query 마이그레이션

## ✅ TO-DO
- [x]  홈 화면 상태관리 react-query 마이그레이션
- [x]  검색창 react-query 마이그레이션
- [x]  상세 화면 react-query 마이그레이션

## 🔔 기타
-
