### ISSUE TITLE
[REFACTOR]: 전반적인 리팩토링 

### ISSUE THREAD

**Issue by durumi99** [FunD-StockProject/StockProject-Frontend#90]
## 📒 설명
전반적인 리팩토링 
- 디자인
- 인터페이스 및 타입

## ✅ TO-DO
- [ ]  스타일 컴포넌트 리팩토링
- [ ]  emotion deep한 적용
- [ ]  인터페이스 및 타입 리팩토링

## 🔔 기타
-
